cors:
  originPatterns: http://localhost:3000,http://localhost:8000,http://localhost:8080
security:
  jwt:
    token:
      secret-key: eoflamengo53
      expire-length: 3600000
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    use-root-path: true
  paths-to-match:
    - /**
    - /auth/**
    - /api/**