spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/financial_management
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect