
cors:
  originPatterns: http://localhost:3000,http://localhost:8000,http://localhost:8080
security:
  jwt:
    token:
      secret-key: eoflamengo
      expire-length: 3600000
spring:
  jackson:
    deserialization:
      accept-empty-string-as-null-object: true
  datasource:
    url: jdbc:postgresql://localhost:5432/financial_management_db
    username: admin
    password: admin123
  jpa:
    hibernate:
      format_sql: true
      ddl-auto: none
    show-sql: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    use-root-path: true
  paths-to-match:
    - /**
    - /auth/**
    - /api/**
server:
  port: 80