version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: financial_db
    environment:
      POSTGRES_DB: financial_management_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    image: elestio/pgadmin
    container_name: meu_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "5001:8080"
    depends_on:
      - db
    restart: always

volumes:
  postgres_data: